name: TeaSpoon
main: CortexPE\Main
version: 1.0.0
api: [3.0.0-ALPHA9]
load: STARTUP
author: CortexPE
description: A PLUGIN to Extend PMMP's Functionality without completely changing it.
website: http://CortexPE.xyz

