# MMP""MM""YMM               .M"""bgd
# P'   MM   `7              ,MI    "Y
#      MM  .gP"Ya   ,6"Yb.  `MMb.   `7MMpdMAo.  ,pW"Wq.   ,pW"Wq.`7MMpMMMb.
#      MM ,M'   Yb 8)   MM    `YMMNq. MM   `Wb 6W'   `Wb 6W'   `Wb MM    MM
#      MM 8M""""""  ,pm9MM  .     `MM MM    M8 8M     M8 8M     M8 MM    MM
#      MM YM.    , 8M   MM  Mb     dM MM   ,AP YA.   ,A9 YA.   ,A9 MM    MM
#    .JMML.`Mbmmd' `Moo9^Yo.P"Ybmmd"  MMbmmd'   `Ybmd9'   `Ybmd9'.JMML  JMML.
#                                     MM
#                                   .JMML.
# TeaSpoon Configuration File

# Config Version Number [DO-NOT-MODIFY]
version: 5

# Weather to register Vanilla Mobs
registerVanillaEntities: true

# Nether & End Dimension
netherName: "nether"
endName: "ender"

# !!!   ONLY ENABLE THIS IF YOU ARE SURE THAT ALL YOUR    !!!
# !!! PLUGINS ARE COMPATIBLE WITH YOUR CURRENT PMMP BUILD !!!
loadAllAPIs: false

# Weather Lightning should cause damage
lightningFire: false

# Ender Pearl Configuration
enderPearlCooldown: 2
enderPearlDamage: 5

# Chorus Fruit Configuration
chorusFruitCooldown: 2